# Generated by Django 2.0.5 on 2018-05-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=60)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
